POST https://vit-ai-docuement.cognitiveservices.azure.com/documentintelligence/documentModels/prebuilt-layout:analyze?api-version=2024-11-30
Content-Type: application/json
Ocp-Apim-Subscription-Key: 

{
  "urlSource": "https://viststracc1ai15jun2026.blob.core.windows.net/docuements/azure_certifications_table.pdf"
}

###
GET  https://vit-ai-docuement.cognitiveservices.azure.com/documentintelligence/documentModels/prebuilt-layout/analyzeResults/2109f1b7-83f7-429f-bad1-5f340b09c610?api-version=2024-11-30
Ocp-Apim-Subscription-Key: 